### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by tangqi9** [xiaweiss/vite-plugin-ali-oss#12]
![20230920105413](https://github.com/xiaweiss/vite-plugin-ali-oss/assets/28030865/164e9af7-765b-4cf8-a8b0-239701f29a7d)

**Comment by xiaweiss** [comment]
从报错里看不出什么问题，辛苦提供下密钥以外的 ali-oss 配置，以及 vite 版本？

**Comment by tangqi9** [comment]
> 从报错里看不出什么问题，辛苦提供下重点以外的ali-oss配置，以及vite版本？

Vite版本：3.1.0
oss没有其他的配置了

**Comment by xiaweiss** [comment]
@tangqi9 vite 3 我去年在生产环境使用过，可以正常使用，请看下项目里 example/vite-3，换成你的密钥试试看呢？

https://github.com/xiaweiss/vite-plugin-ali-oss/tree/main/example/vite-3

**Comment by xiaweiss** [comment]
ali oss upload start 打印出来了，说明 new OSS 和 glob.sync 抓取文件成功了。没有 JS 报错的话，下一个步骤是 client.head 上传单个文件了。报错 403，看起来是网络错误码。建议你排查下打包服务器的网络状态。

**Comment by xiaweiss** [comment]
ali oss upload start 打印出来了，说明 new OSS 和 glob.sync 抓取文件成功了。没有 JS 报错的话，下一个步骤是 client.head 上传单个文件了。报错 403，看起来是网络错误码。建议你排查下打包服务器的网络状态。

**Comment by xiaweiss** [comment]
@tangqi9 好几天没动静了，请问问题解决了吗？

**Comment by xiaweiss** [comment]
没有回复，先关闭问题了。有问题请再开新 issue
