### ISSUE TITLE
windows下资源路径解析错误

### ISSUE THREAD

**Issue by xiankq** [xiaweiss/vite-plugin-ali-oss#14]
<img width="1767" alt="image" src="https://github.com/xiaweiss/vite-plugin-ali-oss/assets/26294948/e6b020dc-29dd-4664-a505-2f0519995a72">

**Comment by xiaweiss** [comment]
🙏 感谢反馈，上游库 glob 的输出有变化，已经合并并发版了。不影响 v1 版本
