### ISSUE TITLE
Request a retry feature

### ISSUE THREAD

**Issue by giiska** [xiaweiss/vite-plugin-ali-oss#16]
Thanks for your masterpiece, I am using your plugin heavily in many of my projects.
I encountered a problem, when a single file upload timeouted and failed during this process of this plugin, it caused the whole Ci task failed. 
I request adding a retry option for each single upload to optimize this.

**Comment by xiaweiss** [comment]
[ali-oss](https://github.com/ali-sdk/ali-oss) does not support retry.

I guess adding a retry count, an interval setting, then add a loop to catch.

**Comment by xiaweiss** [comment]
already support in v2.1.0，add a retry config，type is number
