### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by swift-fs** [xiaweiss/vite-plugin-ali-oss#20]
希望支持bucket子目录的设置，如：bucket/prefix，项目资源会上传到bucket/prefix下

**Comment by xiaweiss** [comment]
我看看哈，请问有阿里云相关的文档吗？

**Comment by swift-fs** [comment]
> 我看看哈，请问有阿里云相关的文档吗？

啊哈哈，不用了，#6 这个能解决我的问题，直接base的url加个subpath就可以了

**Comment by xiaweiss** [comment]
看了文档，ali-oss 包没有提供 bucket/prefix 语法，用 base 就可以
