### ISSUE TITLE
基于本插件开发的vite-plugin-tencent-oss腾讯云oss插件已上传npm

### ISSUE THREAD

**Issue by taosiqi** [xiaweiss/vite-plugin-ali-oss#5]
感谢大佬的一手代码@xiaweiss 
github：https://github.com/taosiqi/vite-plugin-tencent-oss
npm：https://www.npmjs.com/package/vite-plugin-tencent-oss

**Comment by xiaweiss** [comment]
不客气，我们是公司业务里用到了，当时没找到太合适的就自己开发了。欢迎交流
